from enum import StrEnum


class ConversationState(StrEnum):
    NEW = "NEW"
    BOT_ACTIVE = "BOT_ACTIVE"
    ANSWERING_INFORMATION = "ANSWERING_INFORMATION"
    COLLECTING_EVENT_DATA = "COLLECTING_EVENT_DATA"
    QUOTE_REQUEST_READY = "QUOTE_REQUEST_READY"
    WAITING_FOR_APPOINTMENT_DATE = "WAITING_FOR_APPOINTMENT_DATE"
    WAITING_FOR_APPOINTMENT_SELECTION = "WAITING_FOR_APPOINTMENT_SELECTION"
    APPOINTMENT_PENDING_CONFIRMATION = "APPOINTMENT_PENDING_CONFIRMATION"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    WAITING_FOR_HUMAN = "WAITING_FOR_HUMAN"
    HUMAN_ACTIVE = "HUMAN_ACTIVE"
    RETURNED_TO_BOT = "RETURNED_TO_BOT"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
